---
- name: Launch node_exporter container
  community.docker.docker_container:
    name: node_exporter
    image: prom/node-exporter:v1.8.2
    network_mode: host
    pid_mode: host
    state: started
    restart_policy: always
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - 9100:9100
    volumes:
      # Mount the host's /proc directory to the container's /host/proc directory
      # This is necessary for the node_exporter to be able to access the host's metrics
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: [CMD, wget, -q, --spider, http://localhost:9100/metrics]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

- name: Render templated metrics nginx config then request nginx restart
  notify: restart nginx
  ansible.builtin.template:
    src: nginx_metrics.conf.j2
    dest: "{{ ansible_user_home_dir }}/nginx/rendered/include/ext/nginx_metrics.conf"
    mode: "0644"
