---
- name: Synchronize nginx files to remote
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_home_dir }}/nginx"
    delete: true

- name: Make directory for rendered templates
  ansible.builtin.file:
    path: "{{ ansible_user_home_dir }}/nginx/rendered/include/ext"
    state: directory
    mode: "0755"

- name: Render templated datalab config
  ansible.builtin.template:
    src: nginx_datalab.conf.j2
    dest: "{{ ansible_user_home_dir }}/nginx/rendered/include/nginx_datalab.conf"
    mode: "0644"

- name: Render templated SSL config
  ansible.builtin.template:
    src: nginx_ssl.conf.j2
    dest: "{{ ansible_user_home_dir }}/nginx/rendered/nginx_ssl.conf"
    mode: "0644"

- name: Launch nginx container
  community.docker.docker_container:
    name: datalab-nginx
    image: nginx:1.25.3
    network_mode: host
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - "{{ ansible_user_home_dir }}/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ ansible_user_home_dir }}/nginx/rendered/nginx_ssl.conf:/etc/nginx/nginx_ssl.conf"
      - "{{ ansible_user_home_dir }}/nginx/rendered/include:/etc/nginx/include"
    restart_policy: always
